#for API
run_on_failure: Capture Page Screenshot
api_gateway: http://125.235.38.229

client_id: WEB
client_secret: '123456'
accept-language_vi: vi
accept-language_en: en
signature: '1234'

#db_payment
db_payment_name: mm_payment
db_payment_host: 10.255.133.85
db_payment_port: 3306
db_payment_user_name: mm_payment
db_payment_password: 123123a@

#profile
client_id_app: VTPAY

#db_profile
db_profile_name: mm_profile
db_profile_host: 10.255.133.85
db_profile_port: 3306
db_profile_user_name: mm_profile
db_profile_password: 123123a@

#db_payment_history
db_payment_history_name: mm_payment_history
db_payment_history_host: 10.255.133.85
db_payment_history_port: 3306
db_payment_history_user_name: mm_payment_history
db_payment_history_password: 123123a@
